#!/usr/bin/env bash

DOCKER_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd -P )"
PRJ_DIR="$( cd "${DOCKER_DIR}/.." && pwd -P )"

HOST_USER_NAME="$(whoami)"
export HOST_USER_ID="$(id -u "${HOST_USER_NAME}")"
export HOST_GROUP_ID="$(id -g "${HOST_USER_NAME}")"
