#!/usr/bin/env bash

script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd -P )"

source "$script_dir/commonVariables"

docker run                                                                 \
    -it                                                                    \
    --rm                                                                   \
    -u $HOST_USER_ID:$HOST_GROUP_ID                                        \
    -v "$PRJ_DIR":/usr/src/myapp                                          \
    -w /usr/src/myapp                                                      \
    php:7.2-cli                                                            \
    php "$@"
